export const QUEST_REWARD_TITLE_CODES: Readonly<Record<string, readonly string[]>> = {
  dungeon_krypta: ['crypt_hunter', 'undead_slayer'],
  dungeon_kraken: ['kraken_slayer'],
  dungeon_forteca: ['fortress_raider', 'fortress_lord'],
  dungeon_wulkan: ['volcanic_conqueror'],
  dungeon_palac: ['poseidon_champion', 'atlantis_guardian', 'atlantis_master'],
  all_dungeons: ['dungeon_master', 'great_explorer'],
  dungeon_all_bosses: ['dungeon_master', 'great_explorer'],
  bestiary_complete: ['beast_hunter', 'great_discoverer'],
  sea_legend: ['sea_legend'],
  collector_10: ['collector'],
  collector_100: ['treasure_hunter', 'legendary_collector'],
  collector_200: ['grand_collector'],
  collector_300: ['relic_lord'],
  collector_350: ['greatest_explorer'],
  collector_400: ['collection_master'],
  collector_500: ['grand_seeker'],
  legendary_collector_5: ['legendary_hunter'],
  legendary_collector_15: ['legend_collector'],
  legendary_collector_25: ['legend_slayer'],
  legendary_collector_50: ['leviathan_hunter'],
  legendary_collector_75: ['legend_lord'],
  epic_collector_10: ['epic_collector'],
  epic_collector_75: ['relic_sovereign'],
  epic_equipment_full: ['epic_lord'],
  legendary_equipment_full: ['legendary_lord'],
  rare_equipment_full: ['veteran_collector'],
  level_5: ['lvl_rank_5'],
  level_10: ['lvl_rank_10'],
  level_20: ['lvl_rank_20'],
  level_35: ['veteran_captain', 'lvl_rank_35'],
  level_50: ['elite_captain', 'lvl_rank_50'],
  level_75: ['lvl_rank_75'],
  level_100: ['lvl_rank_100'],
  level_150: ['ocean_ruler'],
  level_200: ['immortal_captain'],
  level_225: ['unbeaten_corsair'],
  level_250: ['atlantis_emperor'],
  level_300: ['eternal_captain'],
  fight_won_50: ['fight_veteran_50'],
  fight_veteran_100: ['fight_veteran_100'],
  fight_veteran_250: ['black_corsair'],
  fight_veteran_500: ['undefeated_pirate'],
  fight_veteran_1000: ['ocean_master'],
  fight_veteran_2000: ['expedition_veteran'],
  fight_veteran_7500: ['storm_lord'],
  fight_veteran_10000: ['fight_archmaster'],
  fight_veteran_15000: ['ocean_slayer'],
};

export function titleCodesForQuest(code: string | null | undefined): string[] {
  const key = code?.trim();
  if (!key) return [];
  return [...(QUEST_REWARD_TITLE_CODES[key] ?? [])];
}
